# Generated by Django 3.0.6 on 2020-06-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Confession', '0003_auto_20200614_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confessionpost',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
