# Generated by Django 3.0.6 on 2020-06-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Confession', '0004_auto_20200620_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confessionpost',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
