# Generated by Django 3.0.6 on 2020-06-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Confession', '0005_auto_20200620_2153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
