# Generated by Django 3.0.6 on 2020-06-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, choices=[('lo', 'love'), ('fa', 'family'), ('te', 'technology'), ('sp', 'sports'), ('po', 'politics'), ('tr', 'travel'), ('fu', 'fun'), ('fe', 'feeling'), ('ed', 'education'), ('he', 'health'), ('na', 'nature'), ('ot', 'others')], max_length=2, null=True),
        ),
    ]
