# Generated by Django 3.0.6 on 2020-06-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20200611_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, choices=[('LO', 'Love'), ('BU', 'Business'), ('CU', 'Culture'), ('LI', 'Lifestyle'), ('TE', 'Tech'), ('SP', 'Sports'), ('PO', 'Politics'), ('TR', 'Travel'), ('FU', 'Fun'), ('FE', 'Feeling'), ('FA', 'Fashion'), ('ED', 'Education'), ('HE', 'Health'), ('NA', 'Nature'), ('OT', 'Other')], max_length=2, null=True),
        ),
    ]
