# Generated by Django 3.0.6 on 2020-06-20 04:36

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20200613_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Blog.models.user_directory_path),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
