# Generated by Django 3.0.3 on 2020-06-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20200620_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('LO', 'Love'), ('BU', 'Business'), ('CU', 'Culture'), ('LI', 'Lifestyle'), ('TE', 'Tech'), ('SP', 'Sports'), ('PO', 'Politics'), ('TR', 'Travel'), ('FU', 'Fun'), ('FE', 'Feeling'), ('FA', 'Fashion'), ('ED', 'Education'), ('HE', 'Health'), ('NA', 'Nature'), ('OT', 'Other')], max_length=2),
        ),
    ]
